CREATE TABLE IF NOT EXISTS profiles (
 calendar TEXT PRIMARY KEY REFERENCES calendars(id),
 name TEXT NOT NULL DEFAULT '',
 phone TEXT NOT NULL DEFAULT '',
 city TEXT NOT NULL DEFAULT '',
 bio TEXT NOT NULL DEFAULT '',
 photo TEXT NOT NULL DEFAULT ''
);
