'use client';
import {useCallback,useEffect,useState} from 'react';
import LoginAccess from './login-access';
import Profile from './profile';
import NotificationSettings from './notification-settings';
import {CalendarDays,Clock3,Link2,Plus,ChevronLeft,ChevronRight,ExternalLink,LockKeyhole,Check,CalendarCheck2,Settings2,LogOut,Leaf,Copy,Loader2} from 'lucide-react';
import {SidebarProvider,Sidebar,SidebarContent,SidebarHeader,SidebarFooter,SidebarTrigger} from '@/components/ui/sidebar';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {AlertDialog,AlertDialogContent,AlertDialogTitle,AlertDialogDescription,AlertDialogCancel} from '@/components/ui/alert-dialog';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {Switch} from '@/components/ui/switch';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Toaster,toast} from 'sonner';
import {CalendarData,Booking,defaults,dateKey,todayKey,parseDay,weekdays,timeLabel,minutes,availableSlots} from '@/lib/schedule';

const initial:CalendarData={id:'',name:'Agenda Éden',service:'Atendimento',duration:60,hours:defaults,location:'A combinar',active:1};
const monthLabel=(d:Date)=>d.toLocaleDateString('pt-BR',{month:'long',year:'numeric'});
function addDays(day:string,n:number){const d=parseDay(day);d.setDate(d.getDate()+n);return dateKey(d);}
export function Brand(){return <div className="brand"><span className="brand-mark"><img src="/eden-logo.png" alt=""/></span><span>éden<span className="brand-sub">AGENDA</span></span></div>}
export function MiniCalendar({selected,onSelect,publicMode=false}:{selected:string;onSelect:(v:string)=>void;publicMode?:boolean}){
 const [month,setMonth]=useState(()=>new Date(parseDay(selected).getFullYear(),parseDay(selected).getMonth(),1,12));
 useEffect(()=>{const d=parseDay(selected);setMonth(new Date(d.getFullYear(),d.getMonth(),1,12))},[selected]);
 const start=new Date(month);start.setDate(1-month.getDay());
 return <div className="mini-calendar"><div className="mini-heading"><strong>{monthLabel(month)}</strong><div><button aria-label="Mês anterior" onClick={()=>setMonth(new Date(month.getFullYear(),month.getMonth()-1,1,12))}><ChevronLeft size={16}/></button><button aria-label="Próximo mês" onClick={()=>setMonth(new Date(month.getFullYear(),month.getMonth()+1,1,12))}><ChevronRight size={16}/></button></div></div><div className="mini-grid">{['D','S','T','Q','Q','S','S'].map((w,i)=><span className="weekday" key={i}>{w}</span>)}{Array.from({length:42},(_,i)=>{const d=new Date(start);d.setDate(start.getDate()+i);const key=dateKey(d);const disabled=publicMode&&(key<todayKey()||key>addDays(todayKey(),90));return <button key={key} disabled={disabled} className={`${d.getMonth()!==month.getMonth()?'outside':''} ${key===selected?'selected':''} ${key===todayKey()?'today':''}`} aria-label={d.toLocaleDateString('pt-BR',{dateStyle:'full'})} aria-pressed={key===selected} onClick={()=>onSelect(key)}>{d.getDate()}</button>})}</div></div>
}
export async function api(path:string,body?:unknown,method='POST') {const r=await fetch(path,body?{method,headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:undefined);const data:any=await r.json();if(!r.ok)throw new Error(data.error||'Não foi possível concluir. Tente novamente.');return data;}

export default function Agenda(){
 const [calendar,setCalendar]=useState(initial),[bookings,setBookings]=useState<Booking[]>([]),[selected,setSelected]=useState(todayKey),[view,setView]=useState('week'),[section,setSection]=useState('calendar');
 const [loading,setLoading]=useState(true),[auth,setAuth]=useState(false),[error,setError]=useState(''),[modal,setModal]=useState<'new'|'block'|'share'|null>(null),[detail,setDetail]=useState<Booking|null>(null),[cancel,setCancel]=useState(false),[busy,setBusy]=useState(false);
 const [form,setForm]=useState({date:todayKey(),start:'09:00',end:'10:00',name:'',email:'',phone:''});
 const load=useCallback(async()=>{try{const r=await fetch('/api/admin');if(r.status===401){setAuth(true);return;}const data:any=await r.json();if(!r.ok)throw new Error(data.error);setCalendar(prev=>JSON.stringify(prev)===JSON.stringify(data.calendar)?prev:data.calendar);setBookings(data.bookings);setError('');setAuth(false);}catch(e){setError((e as Error).message)}finally{setLoading(false)}},[]);
 useEffect(()=>{load();const id=setInterval(load,30000);return()=>clearInterval(id)},[load]);
 useEffect(()=>{const context=(document as any).modelContext;if(!context?.registerTool)return;const life=new AbortController();Promise.resolve(context.registerTool({name:'select_calendar_date',title:'Mostrar uma data na agenda',description:'Navega para a data informada no painel. Não cria nem altera reservas.',inputSchema:{type:'object',properties:{date:{type:'string',pattern:'^\\d{4}-\\d{2}-\\d{2}$'}},required:['date'],additionalProperties:false},annotations:{readOnlyHint:true},execute:async(input:any)=>{if(!/^\d{4}-\d{2}-\d{2}$/.test(input.date)||isNaN(parseDay(input.date).getTime())||dateKey(parseDay(input.date))!==input.date)throw new Error('Data inválida');setSelected(input.date);setSection('calendar');return {date:input.date};}},{signal:life.signal})).catch(()=>{});return()=>life.abort()},[]);
 const weekStart=addDays(selected,-parseDay(selected).getDay());const days=Array.from({length:view==='day'?1:7},(_,i)=>view==='day'?selected:addDays(weekStart,i));
 const visible=bookings.filter(b=>days.includes(b.date));const confirmed=visible.filter(b=>b.kind==='booking');const next=bookings.find(b=>b.kind==='booking'&&new Date(`${b.date}T${timeLabel(b.start)}:00-03:00`).getTime()>Date.now());
 const openNew=(kind:'new'|'block',day=selected,start=540)=>{setForm({date:day,start:timeLabel(start),end:timeLabel(Math.min(start+60,1425)),name:'',email:'',phone:''});setModal(kind);setError('')};
 const save=async(e:React.FormEvent)=>{e.preventDefault();setBusy(true);setError('');try{await api('/api/bookings',{...form,calendar:calendar.id,start:minutes(form.start),end:minutes(form.end),kind:modal==='block'?'block':'booking'});setModal(null);toast.success(modal==='block'?'Horário bloqueado.':'Agendamento confirmado.');await load()}catch(e){setError((e as Error).message)}finally{setBusy(false)}};
 const cancelBooking=async()=>{if(!detail)return;setBusy(true);try{await api('/api/bookings',{id:detail.id},'DELETE');setCancel(false);setDetail(null);toast.success('Horário liberado.');await load()}catch(e){toast.error((e as Error).message)}finally{setBusy(false)}};
 const shareLink=()=>`${window.location.origin}/agendar/${calendar.id}`;
 const copy=async()=>{try{await navigator.clipboard.writeText(shareLink());toast.success('Link copiado. Agora é só enviar ao cliente.')}catch{toast.error('Selecione e copie o link abaixo.')}};
 const startHour=Math.min(8,...calendar.hours.filter(h=>h.enabled).map(h=>Math.floor(minutes(h.start)/60)),...visible.map(b=>Math.floor(b.start/60)));
 const endHour=Math.max(19,...calendar.hours.filter(h=>h.enabled).map(h=>Math.ceil(minutes(h.end)/60)),...visible.map(b=>Math.ceil(b.end/60)));
 return <SidebarProvider style={{'--sidebar-width':'252px'} as React.CSSProperties}><Toaster richColors position="top-center"/><a href="#main" className="skip-link">Ir para a agenda</a>
 <Sidebar className="eden-sidebar"><SidebarHeader className="sidebar-brand"><Brand/><Profile calendarId={calendar.id}/></SidebarHeader><SidebarContent className="sidebar-body"><div className="workspace-label">SEU ESPAÇO</div><nav className="main-nav"><button className={section==='calendar'?'active':''} onClick={()=>setSection('calendar')}><CalendarDays size={19}/>Minha agenda</button><button className={section==='settings'?'active':''} onClick={()=>setSection('settings')}><Clock3 size={19}/>Disponibilidade</button><button disabled={!calendar.id} onClick={()=>setModal('share')}><Link2 size={19}/>Página de agendamento</button></nav><div className="sidebar-divider"/><MiniCalendar selected={selected} onSelect={v=>{setSelected(v);setSection('calendar')}}/><div className="sidebar-divider"/><div className="legend"><span><i className="legend-confirmed"/>Agendamentos</span><span><i className="legend-available"/>Horários disponíveis</span><span><i className="legend-blocked"/>Bloqueios</span></div><div className="sidebar-tip"><span className="tip-icon"><Link2 size={18}/></span><strong>Sua agenda, a um link.</strong><p>Deixe seus clientes escolherem o melhor horário.</p><button onClick={()=>setModal('share')} disabled={!calendar.id}>Compartilhar agenda <Copy size={14}/></button></div></SidebarContent><SidebarFooter className="sidebar-account">{calendar.id&&<a onClick={async e=>{e.preventDefault();await fetch("/api/auth",{method:"DELETE"});window.location.href="/signout-with-chatgpt?return_to=/"}} href="/signout-with-chatgpt?return_to=/" aria-label="Sair da conta" target="_top"><LogOut size={17}/></a>}</SidebarFooter></Sidebar>
 <main id="main" className="dashboard"><header className="topbar"><div className="breadcrumb"><SidebarTrigger className="mobile-menu"/><span>Meu espaço</span><span className="crumb-separator">/</span><strong>{section==='settings'?'Disponibilidade':'Minha agenda'}</strong></div><div className="topbar-right"><span className="timezone"><Clock3 size={14}/>Horário de Brasília</span><span className="avatar small">É</span></div></header>
 <div className="dashboard-inner"><div className="page-heading"><div><div className="eyebrow">ORGANIZE SEU TEMPO</div><h1>{section==='settings'?'Disponibilidade':'Minha agenda'}<span className="heading-dot">.</span></h1><p>{section==='settings'?'Defina quando seus clientes podem marcar com você.':'Um espaço para seus horários. Mais tempo para você.'}</p></div><div className="heading-actions"><button className="btn secondary" disabled={!calendar.id} onClick={()=>setModal('share')}><Link2 size={17}/>Compartilhar link</button><button className="btn primary" disabled={!calendar.id} onClick={()=>openNew('new')}><Plus size={18}/>Novo agendamento</button></div></div>
 {auth&&<div className="auth-gate"><LoginAccess/></div>}
 {error&&!modal&&<div role="alert" className="notice error">{error}<button onClick={load}>Tentar novamente</button></div>}
 {section==='settings'?<Settings calendar={calendar} onSaved={load}/>:<><div className="overview"><div className="overview-item"><span className="overview-icon green"><CalendarCheck2 size={20}/></span><div><span>Agendamentos {view==='day'?'no dia':'na semana'}</span><strong>{loading?'—':confirmed.length.toString().padStart(2,'0')}<small>confirmados</small></strong></div></div><div className="overview-item"><span className="overview-icon amber"><Clock3 size={20}/></span><div><span>Tempo reservado</span><strong>{loading?'—':`${confirmed.reduce((n,b)=>n+b.end-b.start,0)/60}h`}<small>{view==='day'?'neste dia':'nesta semana'}</small></strong></div></div><div className="overview-item next"><span className="overview-icon mint"><CalendarDays size={20}/></span><div><span>Próximo atendimento</span><strong className="next-name">{next?next.name:'Seu próximo encontro'}<small>{next?`${parseDay(next.date).toLocaleDateString('pt-BR',{day:'2-digit',month:'2-digit'})} às ${timeLabel(next.start)}`:'As novas reservas aparecem aqui'}</small></strong></div></div></div>
 <section className="calendar-panel" aria-label="Calendário de agendamentos"><div className="calendar-toolbar"><div className="month-navigation"><h2>{monthLabel(parseDay(selected))}</h2><div className="arrow-group"><button aria-label="Período anterior" onClick={()=>setSelected(addDays(selected,view==='day'?-1:-7))}><ChevronLeft size={18}/></button><button aria-label="Próximo período" onClick={()=>setSelected(addDays(selected,view==='day'?1:7))}><ChevronRight size={18}/></button></div><button className="today-btn" onClick={()=>setSelected(todayKey())}>Hoje</button></div><div className="view-controls"><button className="block-button" disabled={!calendar.id} onClick={()=>openNew('block')}><LockKeyhole size={15}/><span>Bloquear horário</span></button><Tabs value={view} onValueChange={setView}><TabsList><TabsTrigger value="day">Dia</TabsTrigger><TabsTrigger value="week">Semana</TabsTrigger></TabsList></Tabs></div></div>
 <div className={`calendar-scroll ${view==='day'?'single-day':''}`}><div className="calendar-grid" style={{'--days':days.length} as React.CSSProperties}><div className="day-headers"><div className="grid-zone">GMT−03</div>{days.map(day=><button key={day} className={`day-heading ${day===todayKey()?'current':''}`} onClick={()=>{setSelected(day);setView('day')}}><span>{weekdays[parseDay(day).getDay()].slice(0,3).toUpperCase()}</span><strong>{parseDay(day).getDate()}</strong>{day===todayKey()&&<small>HOJE</small>}</button>)}</div><div className="week-body" style={{height:(endHour-startHour)*64}}><div className="time-labels">{Array.from({length:endHour-startHour},(_,i)=><span key={i} style={{top:i*64}}>{timeLabel((startHour+i)*60)}</span>)}</div>{days.map(day=><div className={`day-column ${day===todayKey()?'current-col':''}`} key={day}>{Array.from({length:endHour-startHour},(_,i)=><button key={i} disabled={!calendar.id} className="hour-cell" aria-label={`Criar agendamento em ${day} às ${timeLabel((startHour+i)*60)}`} onClick={()=>openNew('new',day,(startHour+i)*60)}/>)}{calendar.hours[parseDay(day).getDay()].enabled&&<div className="availability-band" style={{top:(minutes(calendar.hours[parseDay(day).getDay()].start)/60-startHour)*64,height:(minutes(calendar.hours[parseDay(day).getDay()].end)-minutes(calendar.hours[parseDay(day).getDay()].start))/60*64}}><span>Disponível</span></div>}{visible.filter(b=>b.date===day).map(b=><button key={b.id} className={`appointment ${b.kind==='block'?'blocked':''}`} style={{top:(b.start/60-startHour)*64+2,height:Math.max((b.end-b.start)/60*64-4,24)}} onClick={()=>setDetail(b)}><strong>{b.kind==='block'?<><LockKeyhole size={12}/>Bloqueado</>:b.name}</strong><span>{timeLabel(b.start)} – {timeLabel(b.end)}</span>{b.end-b.start>=60&&b.kind!=='block'&&<small>{calendar.service}</small>}</button>)}</div>)}</div></div></div><footer className="calendar-footer"><span><span className="status-dot"/>{calendar.active?'Agendamentos online ativados':'Agendamentos online pausados'}</span><span>Clique em um horário para agendar</span></footer></section></>}
 <footer className="page-footer"><span>Seu tempo, bem cuidado.</span><span>éden agenda</span></footer></div></main>
 <Dialog open={!!modal} onOpenChange={v=>{if(!v){setModal(null);setError('')}}}><DialogContent className="eden-modal"><DialogTitle>{modal==='share'?'Compartilhe sua agenda':modal==='block'?'Bloquear um horário':'Novo agendamento'}</DialogTitle><DialogDescription>{modal==='share'?'Seu cliente escolhe um horário disponível e confirma a reserva.':modal==='block'?'Este período ficará indisponível para novos agendamentos.':'Escolha o horário e preencha os dados do cliente.'}</DialogDescription>{modal==='share'?<div className="share-content"><div className="share-preview"><Brand/><h3>{calendar.name}</h3><p>{calendar.service} · {calendar.duration} minutos</p><span className="badge"><Check size={13}/>Agendamento online</span></div><label>Link para seus clientes<input readOnly value={calendar.id?shareLink():''} onFocus={e=>e.target.select()}/></label><button className="btn primary" onClick={copy}><Copy size={17}/>Copiar link</button><a className="btn secondary" href={`/agendar/${calendar.id}`} target="_blank" rel="noreferrer"><ExternalLink size={17}/>Visualizar página do cliente</a></div>:<form onSubmit={save} className="form-stack"><label>Data<input type="date" required min={todayKey()} max={addDays(todayKey(),90)} value={form.date} onChange={e=>setForm({...form,date:e.target.value})}/></label><div className="form-row"><label>Horário de início<input type="time" required step="900" value={form.start} onChange={e=>setForm({...form,start:e.target.value})}/></label>{modal==='block'?<label>Horário de término<input type="time" required step="900" value={form.end} onChange={e=>setForm({...form,end:e.target.value})}/></label>:<div className="duration-note"><Clock3 size={17}/>{calendar.duration} minutos</div>}</div>{modal==='new'&&<><label>Nome do cliente<input autoComplete="name" maxLength={100} required value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="Nome completo"/></label><label>E-mail<input type="email" autoComplete="email" maxLength={160} required value={form.email} onChange={e=>setForm({...form,email:e.target.value})} placeholder="cliente@email.com"/></label><label>WhatsApp com DDD<input type="tel" autoComplete="tel" required minLength={10} maxLength={30} value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></label></>}{error&&<p role="alert" className="form-error">{error}</p>}<button className="btn primary" disabled={busy}>{busy?<Loader2 className="spin" size={18}/>:modal==='block'?<LockKeyhole size={17}/>:<Check size={17}/>} {busy?'Salvando…':modal==='block'?'Bloquear horário':'Confirmar agendamento'}</button></form>}</DialogContent></Dialog>
 <Dialog open={!!detail&&!cancel} onOpenChange={v=>{if(!v)setDetail(null)}}><DialogContent className="eden-modal"><DialogTitle>{detail?.name}</DialogTitle><DialogDescription>{detail?.kind==='block'?'Período indisponível para reservas.':'Agendamento confirmado'}</DialogDescription>{detail&&<div className="detail-content"><p><CalendarDays size={18}/>{parseDay(detail.date).toLocaleDateString('pt-BR',{dateStyle:'full'})}</p><p><Clock3 size={18}/>{timeLabel(detail.start)} – {timeLabel(detail.end)}</p>{detail.email&&<p>{detail.email}</p>}{detail.phone&&<p>{detail.phone}</p>}<button className="btn danger" onClick={()=>setCancel(true)}>{detail.kind==='block'?'Desbloquear horário':'Cancelar agendamento'}</button></div>}</DialogContent></Dialog>
 <AlertDialog open={cancel} onOpenChange={setCancel}><AlertDialogContent className="eden-modal"><AlertDialogTitle>Liberar este horário?</AlertDialogTitle><AlertDialogDescription>A reserva será removida e o horário poderá ser agendado novamente. O cliente não receberá uma notificação automática.</AlertDialogDescription><div className="form-row"><AlertDialogCancel className="btn secondary">Voltar</AlertDialogCancel><button className="btn danger" disabled={busy} onClick={cancelBooking}>{busy?'Removendo…':'Sim, liberar horário'}</button></div></AlertDialogContent></AlertDialog>
 </SidebarProvider>
}

function Settings({calendar,onSaved}:{calendar:CalendarData;onSaved:()=>Promise<void>}){
 const [draft,setDraft]=useState(calendar),[saving,setSaving]=useState(false),[error,setError]=useState('');useEffect(()=>setDraft(calendar),[calendar]);
 const submit=async(e:React.FormEvent)=>{e.preventDefault();setSaving(true);setError('');try{await api('/api/admin',draft,'PATCH');await onSaved();toast.success('Disponibilidade atualizada.')}catch(e){setError((e as Error).message)}finally{setSaving(false)}};
 return <form onSubmit={submit} className="settings-grid"><section className="settings-card"><div className="card-heading"><Clock3 size={21}/><div><h2>Horários de atendimento</h2><p>Uma rotina semanal, do seu jeito.</p></div></div>{weekdays.map((day,i)=><div className="hours-row" key={day}><Switch checked={draft.hours[i].enabled} aria-label={`Atender ${day}`} onCheckedChange={enabled=>setDraft({...draft,hours:draft.hours.map((h,j)=>j===i?{...h,enabled}:h)})}/><strong>{day}</strong>{draft.hours[i].enabled?<div className="hour-inputs"><input aria-label={`Início ${day}`} type="time" required step="900" value={draft.hours[i].start} onChange={e=>setDraft({...draft,hours:draft.hours.map((h,j)=>j===i?{...h,start:e.target.value}:h)})}/><span>até</span><input aria-label={`Fim ${day}`} type="time" required step="900" value={draft.hours[i].end} onChange={e=>setDraft({...draft,hours:draft.hours.map((h,j)=>j===i?{...h,end:e.target.value}:h)})}/></div>:<span className="muted">Não disponível</span>}</div>)}<p className="settings-note">Horário de Brasília (GMT−03). Alterações não cancelam reservas existentes.</p></section><section className="settings-card form-stack"><div className="card-heading"><Settings2 size={21}/><div><h2>Sua página de agendamento</h2><p>Informações que seus clientes verão.</p></div></div><label>Nome da agenda<input required maxLength={80} value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})}/></label><label>Nome do atendimento<input required maxLength={80} value={draft.service} onChange={e=>setDraft({...draft,service:e.target.value})}/></label><label>Duração<Select value={String(draft.duration)} onValueChange={v=>setDraft({...draft,duration:Number(v)})}><SelectTrigger className="duration-select"><SelectValue/></SelectTrigger><SelectContent>{[15,30,45,60,90,120].map(n=><SelectItem key={n} value={String(n)}>{n} minutos</SelectItem>)}</SelectContent></Select></label><label>Local ou instruções<input maxLength={160} value={draft.location} onChange={e=>setDraft({...draft,location:e.target.value})}/></label><label className="active-setting"><span>Receber agendamentos online</span><Switch checked={!!draft.active} onCheckedChange={v=>setDraft({...draft,active:v?1:0})}/></label>{error&&<p role="alert" className="form-error">{error}</p>}{calendar.id&&<NotificationSettings/>}<button className="btn primary" disabled={saving||!calendar.id}>{saving?'Salvando…':'Salvar alterações'}</button></section></form>
}

