'use client';
import {useEffect,useState} from 'react';
import {InputOTP,InputOTPGroup,InputOTPSlot} from '@/components/ui/input-otp';
export default function LoginAccess(){
 const [ready,setReady]=useState(false),[email,setEmail]=useState(''),[code,setCode]=useState(''),[stage,setStage]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[wait,setWait]=useState(0);
 useEffect(()=>{fetch('/api/auth').then(r=>r.json()).then((d:any)=>setReady(d.emailLoginReady)).catch(()=>{})},[]);
 useEffect(()=>{if(!wait)return;const t=setTimeout(()=>setWait(v=>v-1),1000);return()=>clearTimeout(t)},[wait]);
 const submit=async(e:React.FormEvent,resend=false)=>{e.preventDefault();setBusy(true);setError('');try{const r=await fetch('/api/auth',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email,...(stage&&!resend?{code}:{})})});const d:any=await r.json();if(!r.ok)throw new Error(d.error);if(stage&&!resend){window.location.reload();return}setStage(true);setCode('');setWait(60)}catch(e){setError((e as Error).message)}finally{setBusy(false)}};
 return <section className="email-login"><div><strong>Acesse sua agenda pelo e-mail</strong><p>{stage?`Enviamos um código para ${email}. Confira também o spam.`:'Entre para gerenciar seus horários e receber avisos de novas reservas.'}</p></div>{ready?<form onSubmit={submit} className="form-stack">{!stage?<label htmlFor="login-email">Seu e-mail<input id="login-email" type="email" autoComplete="email" maxLength={160} required value={email} onChange={e=>setEmail(e.target.value)} placeholder="voce@email.com"/></label>:<><label htmlFor="login-code">Código de acesso<InputOTP id="login-code" maxLength={8} value={code} onChange={setCode} inputMode="numeric" autoComplete="one-time-code" pattern="[0-9]*"><InputOTPGroup>{[0,1,2,3,4,5,6,7].map(i=><InputOTPSlot key={i} index={i}/>)}</InputOTPGroup></InputOTP></label><div className="login-links"><button type="button" disabled={!!wait||busy} onClick={e=>submit(e,true)}>{wait?`Reenviar em ${wait}s`:'Reenviar código'}</button><button type="button" disabled={busy} onClick={()=>{setStage(false);setCode('');setError('')}}>Trocar e-mail</button></div></>}{error&&<p role="alert" className="form-error">{error}</p>}<button className="btn primary" disabled={busy||(stage&&code.length!==8)}>{busy?'Aguarde…':stage?'Entrar na minha agenda':'Enviar código de acesso'}</button></form>:<p className="settings-note">O acesso por e-mail está em preparação. Você pode continuar acessando sua agenda existente abaixo.</p>}<details className="legacy-login"><summary>Já tenho uma agenda criada anteriormente</summary><p>Entre uma vez pelo acesso anterior para vincular sua agenda ao mesmo e-mail. Depois, use o código de acesso.</p><a className="btn secondary" href="/signin-with-chatgpt?return_to=/" target="_top">Vincular agenda existente</a></details></section>
}

