'use client';
import {useEffect,useState} from 'react';
import {Pencil,Camera} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
const empty={name:'',phone:'',city:'',bio:'',photo:''};
export default function Profile({calendarId}:{calendarId:string}){
 const [profile,setProfile]=useState(empty),[draft,setDraft]=useState(empty),[email,setEmail]=useState(''),[open,setOpen]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');
 useEffect(()=>{if(!calendarId)return;let alive=true;fetch('/api/profile').then(async r=>{const d=await r.json() as {profile:typeof empty;email:string;error?:string};if(!r.ok)throw Error(d.error||"Falha ao salvar o perfil.");if(alive){setProfile(d.profile);setEmail(d.email)}}).catch(()=>{if(alive)setError('Não foi possível carregar seu perfil. Recarregue a página.')});return()=>{alive=false}},[calendarId]);
 async function photo(file?:File){if(!file)return;setError('');if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>5*1024*1024){setError('Escolha JPG, PNG ou WebP de até 5 MB.');return}setBusy(true);try{const bitmap=await createImageBitmap(file);const canvas=document.createElement('canvas');canvas.width=canvas.height=320;const ctx=canvas.getContext('2d')!;ctx.fillStyle='#fff';ctx.fillRect(0,0,320,320);const size=Math.min(bitmap.width,bitmap.height);ctx.drawImage(bitmap,(bitmap.width-size)/2,(bitmap.height-size)/2,size,size,0,0,320,320);bitmap.close();setDraft(v=>({...v,photo:canvas.toDataURL('image/jpeg',.82)}))}catch{setError('Não foi possível abrir a foto. Escolha outra imagem.')}finally{setBusy(false)}}
 async function save(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{const r=await fetch('/api/profile',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(draft)});const d=await r.json() as {profile:typeof empty;email:string;error?:string};if(!r.ok)throw Error(d.error||"Falha ao salvar o perfil.");setProfile(draft);setOpen(false)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 return <><button className="profile-trigger" disabled={!calendarId} onClick={()=>{setDraft(profile);setOpen(true)}} aria-label="Editar meu perfil"><span className="avatar">{profile.photo?<img src={profile.photo} alt=""/>:profile.name.charAt(0).toUpperCase()||'É'}</span><span><strong>{profile.name||'Meu espaço'}</strong><small>Editar meu perfil</small></span><Pencil size={15}/></button><Dialog open={open} onOpenChange={v=>{if(!busy)setOpen(v)}}><DialogContent className="eden-modal profile-modal"><DialogTitle>Meu perfil</DialogTitle><DialogDescription>Personalize seu espaço. Estes dados ficam privados no seu painel.</DialogDescription><form className="form-stack" onSubmit={save}><div className="profile-photo"><span className="avatar">{draft.photo?<img src={draft.photo} alt="Prévia da foto de perfil"/>:draft.name.charAt(0).toUpperCase()||'É'}</span><div><label className="btn secondary"><Camera size={16}/>Adicionar foto<input type="file" accept="image/jpeg,image/png,image/webp" disabled={busy} onChange={e=>{photo(e.target.files?.[0]);e.target.value=''}}/></label><small>JPG, PNG ou WebP · até 5 MB</small>{draft.photo&&<button type="button" disabled={busy} onClick={()=>setDraft({...draft,photo:''})}>Remover foto</button>}</div></div><label>Nome de exibição<input required maxLength={80} autoComplete="name" value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})}/></label><label>E-mail da conta<input readOnly value={email}/></label><label>WhatsApp / telefone<input type="tel" maxLength={30} autoComplete="tel" value={draft.phone} onChange={e=>setDraft({...draft,phone:e.target.value})} placeholder="(11) 91234-5678"/></label><label>Cidade<input maxLength={100} autoComplete="address-level2" value={draft.city} onChange={e=>setDraft({...draft,city:e.target.value})}/></label><label>Sobre você<textarea rows={3} maxLength={500} value={draft.bio} onChange={e=>setDraft({...draft,bio:e.target.value})} placeholder="Uma breve apresentação"/></label>{error&&<p role="alert" className="form-error">{error}</p>}<button className="btn primary" disabled={busy}>{busy?'Salvando…':'Salvar perfil'}</button></form></DialogContent></Dialog></>;
}
