// Provider doubles are scoped to this Node process; no test bypass is built into the app.
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {registerHooks} from 'node:module';
import {readFileSync} from 'node:fs';
import {fileURLToPath,pathToFileURL} from 'node:url';
import path from 'node:path';
const root=path.resolve(fileURLToPath(new URL('..',import.meta.url)));
const sqlite=new DatabaseSync(':memory:');
for(const file of ['0000_cool_mojo.sql','0001_reflective_peter_parker.sql'])sqlite.exec(readFileSync(path.join(root,'drizzle',file),'utf8').replaceAll('--> statement-breakpoint',''));
const d1={prepare(sql){return {values:[],bind(...values){this.values=values;return this},async first(){return sqlite.prepare(sql).get(...this.values)||null},async all(){return {results:sqlite.prepare(sql).all(...this.values)}},async run(){return {success:true,meta:sqlite.prepare(sql).run(...this.values)}}}},async batch(statements){sqlite.exec('BEGIN');try{const result=[];for(const statement of statements)result.push(await statement.run());sqlite.exec('COMMIT');return result}catch(e){sqlite.exec('ROLLBACK');throw e}}};
const cookieValues=new Map();const cookieOptions=new Map();let legacy=null;
globalThis.edenTest={env:{DB:d1},cookies:{get:key=>cookieValues.has(key)?{value:cookieValues.get(key)}:undefined,set:(key,value,options)=>{cookieValues.set(key,value);cookieOptions.set(key,options)},delete:key=>cookieValues.delete(key)},legacy:()=>legacy};
registerHooks({resolve(specifier,context,next){if(specifier==='cloudflare:workers')return {url:'eden-test:env',shortCircuit:true};if(specifier==='next/headers')return {url:'eden-test:headers',shortCircuit:true};if(specifier==='@/app/chatgpt-auth')return {url:'eden-test:legacy',shortCircuit:true};if(specifier.startsWith('@/'))return next(pathToFileURL(path.join(root,specifier.slice(2)+'.ts')).href,context);if(specifier.startsWith('.')&&context.parentURL?.endsWith('.ts')&&!path.extname(specifier))return next(new URL(specifier+'.ts',context.parentURL).href,context);return next(specifier,context)},load(url,context,next){const sources={'eden-test:env':'export const env=globalThis.edenTest.env;','eden-test:headers':'export async function cookies(){return globalThis.edenTest.cookies}','eden-test:legacy':'export async function getChatGPTUser(){return globalThis.edenTest.legacy()}'};return sources[url]?{format:'module',source:sources[url],shortCircuit:true}:next(url,context)}});
const auth=await import('../app/api/auth/route.ts');const {ownCalendar}=await import('../lib/server.ts');const notifications=await import('../lib/notifications.ts');
const env=globalThis.edenTest.env;const origin='https://agenda.test';const request=(body,headers={})=>new Request(origin+'/api/auth',{method:'POST',headers:{origin,'content-type':'application/json',...headers},body:JSON.stringify(body)});
assert.equal((await auth.POST(request({email:'owner@example.com'}))).status,503);
assert.equal((await auth.POST(request({email:'owner@example.com'},{origin:'https://other.test'}))).status,403);
env.SUPABASE_URL='https://fixture.supabase.co';env.SUPABASE_ANON_KEY='sb_publishable_fixture';let email='owner@example.com';let userId='00000000-0000-4000-8000-000000000001';let emailFail=false;const deliveries=[];let otpRequests=0;
globalThis.fetch=async(url,options={})=>{const address=String(url);const body=JSON.parse(options.body||'{}');if(address.endsWith('/auth/v1/otp')){otpRequests++;return Response.json({})}if(address.endsWith('/auth/v1/verify')){if(body.token!=='123456')return Response.json({msg:'Invalid code'},{status:403});return Response.json({access_token:'fixture_access',refresh_token:'fixture_refresh',token_type:'bearer',expires_in:3600,user:{id:userId,email,email_confirmed_at:new Date().toISOString(),aud:'authenticated',created_at:new Date().toISOString()}})}if(address==='https://api.resend.com/emails'){deliveries.push({body,key:options.headers['Idempotency-Key']});return emailFail?Response.json({error:'Unavailable'},{status:503}):Response.json({id:'fixture_delivery'})}throw new Error('Unexpected network call')};
assert.equal((await auth.POST(request({email}))).status,200);assert.equal(otpRequests,1);
assert.equal((await auth.POST(request({email,code:'000000'}))).status,400);assert.equal(cookieValues.size,0);
assert.equal((await auth.POST(request({email,code:'123456'}))).status,200);
assert.ok(cookieOptions.get('eden_session').httpOnly&&cookieOptions.get('eden_session').secure);assert.equal(cookieOptions.get('eden_session').sameSite,'lax');
const rawToken=cookieValues.get('eden_session');assert.notEqual(sqlite.prepare('SELECT hash FROM email_sessions').get().hash,rawToken);
const original=await ownCalendar(true);assert.equal(original.owner_email,email);
legacy={userId:'old-platform-owner',email};cookieValues.clear();await d1.prepare('INSERT INTO calendars (id,owner,name,service,duration,hours,location,active) VALUES (?,?,?,?,?,?,?,1)').bind('old-calendar',legacy.userId,'Existing agenda','Service',60,original.hours?JSON.stringify(original.hours):'[]','Place').run();
assert.equal((await ownCalendar()).id,'old-calendar');legacy=null;
assert.equal((await auth.POST(request({email,code:'123456'}))).status,200);assert.equal((await ownCalendar()).id,'old-calendar');
const ownerCookie=cookieValues.get('eden_session');email='other@example.com';userId='00000000-0000-4000-8000-000000000002';assert.equal((await auth.POST(request({email,code:'123456'}))).status,200);const other=await ownCalendar(true);assert.notEqual(other.id,'old-calendar');
assert.equal((await auth.DELETE(new Request(origin+'/api/auth',{method:'DELETE',headers:{origin}}))).status,200);assert.equal(await ownCalendar(),null);
cookieValues.set('eden_session','f'.repeat(64));assert.equal(await ownCalendar(),null);
cookieValues.set('eden_session',ownerCookie); // previous login revoked the older session
assert.equal(await ownCalendar(),null);cookieValues.clear();
email='owner@example.com';userId='00000000-0000-4000-8000-000000000001';await auth.POST(request({email,code:'123456'}));const calendar=await ownCalendar();
sqlite.prepare('UPDATE email_sessions SET expires=0').run();assert.equal(await ownCalendar(),null);cookieValues.clear();
const statements=notifications.notificationStatements(calendar,{name:'Client',email:'client@example.com',phone:'',date:'2026-10-20',start:540},'test-booking',600);await d1.batch(statements);
assert.equal((await notifications.sendPending(calendar.id)).configured,false);assert.equal(deliveries.length,0);
env.RESEND_API_KEY='fixture_key';env.EMAIL_FROM='Agenda <agenda@example.com>';emailFail=true;assert.equal((await notifications.sendPending(calendar.id)).pending,true);assert.equal(sqlite.prepare("SELECT count(*) AS n FROM email_outbox WHERE status='sent'").get().n,0);
emailFail=false;const result=await notifications.sendPending(calendar.id);assert.equal(result.sent,2);assert.ok(deliveries.some(d=>d.body.to.includes('client@example.com')));assert.ok(deliveries.some(d=>d.body.to.includes('owner@example.com')));assert.equal(deliveries[0].key,deliveries[2].key);assert.equal((await notifications.sendPending(calendar.id)).sent,0);
sqlite.prepare("INSERT INTO email_outbox (id,calendar,recipient,subject,body,status,created) VALUES ('expired',?,'client@example.com','Subject','Body','pending',0)").run(calendar.id);assert.equal((await notifications.sendPending(calendar.id)).sent,0);
for(let i=0;i<3;i++)await auth.POST(request({email:'limited@example.com'}));assert.equal((await auth.POST(request({email:'limited@example.com'}))).status,429);
assert.ok(!(await (await auth.GET()).text()).includes('fixture_access'));
console.log('PASS: configuration guard, CSRF, OTP verification, hashed secure sessions, legacy linking, user isolation, logout/revocation, expiry, email outbox, failure/retry, idempotency, expired retries, rate limits. Providers mocked; no real email sent.');
sqlite.close();
