import assert from 'node:assert/strict';
const origin='http://127.0.0.1:5173';
const login=await fetch(origin+'/signin-with-chatgpt?return_to=/',{redirect:'manual'});
const cookie=login.headers.get('set-cookie')?.split(';')[0];assert.ok(cookie,'Mock auth session');
const call=async(path,{body,method='GET',auth=false}={})=>{const r=await fetch(origin+path,{method,headers:{...(auth?{Cookie:cookie}:{}),...(body?{'Content-Type':'application/json',Origin:origin}:{})},...(body?{body:JSON.stringify(body)}:{})});return {status:r.status,data:await r.json()}};
assert.equal((await call('/api/admin')).status,401);
const admin=await call('/api/admin',{auth:true});assert.equal(admin.status,200,JSON.stringify(admin.data));
const c=admin.data.calendar;const tomorrow=new Date();tomorrow.setDate(tomorrow.getDate()+1);while([0,6].includes(tomorrow.getDay()))tomorrow.setDate(tomorrow.getDate()+1);const date=tomorrow.toISOString().slice(0,10);
const endpoint=`/api/public?id=${c.id}&date=${date}`;
const pub=await call(endpoint);assert.equal(pub.status,200);assert.ok(!JSON.stringify(pub.data).includes('owner'));assert.ok(pub.data.slots.includes(540));
const body={calendar:c.id,date,start:540,name:'Cliente de teste',email:'teste@example.com',phone:'',kind:'booking'};
const race=await Promise.all([call('/api/bookings',{method:'POST',body}),call('/api/bookings',{method:'POST',body})]);assert.deepEqual(race.map(r=>r.status).sort(),[201,409]);
const booking=race.find(r=>r.status===201).data;
assert.ok(!(await call(endpoint)).data.slots.includes(540));
assert.equal((await call('/api/bookings',{method:'DELETE',body:{id:booking.id}})).status,401);
const block=await call('/api/bookings',{auth:true,method:'POST',body:{calendar:c.id,date,start:570,end:630,kind:'block'}});assert.equal(block.status,409);
const invalid=await call('/api/bookings',{method:'POST',body:{...body,date:'2026-02-30'}});assert.equal(invalid.status,400);
await call('/api/bookings',{auth:true,method:'DELETE',body:{id:booking.id}});
assert.ok((await call(endpoint)).data.slots.includes(540));
const saved=await call('/api/admin',{auth:true,method:'PATCH',body:{...c,duration:30}});assert.equal(saved.status,200);assert.equal((await call('/api/admin',{auth:true})).data.calendar.duration,30);
const blocked=await call('/api/bookings',{auth:true,method:'POST',body:{calendar:c.id,date,start:540,end:600,kind:'block'}});assert.equal(blocked.status,201);const after=(await call(endpoint)).data;assert.ok(!after.slots.includes(540)&&!after.slots.includes(570));assert.ok(after.slots.includes(600));
await call('/api/bookings',{auth:true,method:'DELETE',body:{id:blocked.data.id}});
await call('/api/admin',{auth:true,method:'PATCH',body:{...c,active:0}});assert.equal((await call(endpoint)).data.slots.length,0);assert.equal((await call('/api/bookings',{method:'POST',body})).status,409);
await call('/api/admin',{auth:true,method:'PATCH',body:c});
assert.equal((await call('/api/admin',{auth:true})).data.bookings.length,0);
assert.equal((await fetch(origin+`/agendar/${c.id}`)).status,200);
console.log('PASS: login, private data, concurrent booking, conflict rollback, cancel, invalid date, saved settings, blocked intervals, paused calendar, public page. Test records removed.');
